name: Latest blog-update activity
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "TISTORY"
          feed_list: "https://develop-cr-study.tistory.com/rss"
          template: "<tr><td>$title</td><td>$url</td></tr>"
